apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appPrefix }}-mysql-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appPrefix }}-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
