apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appPrefix }}-mysql-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appPrefix }}-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: {{ .Values.appPrefix }}-mysql
