apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw-wordpress-pvc
  namespace: homework
  labels:
    app: hw-wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
