apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-mysql
  namespace: homework
  labels:
    app: hw-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-mysql
  template:
    metadata:
      labels:
        app: hw-mysql
    spec:
      containers:
        - image: arm64v8/mysql:8.0
          name: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hw-mysql-root-pass
                key: password
          - name: MYSQL_DATABASE
            value: wp_db
          - name: MYSQL_USER
            value: wp_user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hw-mysql-user-pass
                key: password
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
          - name: hw-mysql-storage
            mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
          livenessProbe:
            exec:
              command: ["mysqladmin", "-uroot", "-p$MYSQL_ROOT_PASSWORD", "ping"]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: [ "mysqladmin", "-uroot", "-p$MYSQL_ROOT_PASSWORD", "ping" ]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
      - name: hw-mysql-storage
        persistentVolumeClaim:
          claimName: hw-mysql-pvc
