apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw-mysql-pvc
  namespace: homework
  labels:
    app: hw-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
