---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appPrefix }}-wordpress-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appPrefix }}-wordpress
data:
  WORDPRESS_HTACCESS_OVERRIDE_NONE: "no"
  WORDPRESS_ENABLE_HTACCESS_PERSISTENCE: "no"
  WORDPRESS_BLOG_NAME: "Jakub's Blog"
  WORDPRESS_SKIP_BOOTSTRAP: "no"
