apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appPrefix }}-wordpress-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appPrefix }}-wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appPrefix }}-wordpress
