appPrefix: hw
namespace: homework

mysql:
  image:
    name: mysql
    tag: 8.0
  rootPassword: rootPassABC
  userPassword: userPassXYZ

wordpress:
  image:
    name: docker.io/bitnami/wordpress
    tag: 6.1.1

quota:
  cpu: "2"
  memory: 2Gi
